### ISSUE TITLE
win10系统环境下，启动报错：UnicodeDecodeError: 'gbk' codec can't decode byte 0x9c in position 408: illegal multibyte sequence

### ISSUE THREAD

**Issue by chouniu666** [Crossme0809/gpt-story-genius#1]
PS F:\gpt-story-genius> gradio run.py
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\gradio.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\gradio\cli.py", line 21, in cli
    gradio.reload.main()
  File "C:\Python311\Lib\site-packages\gradio\reload.py", line 88, in main
    filename, path, watch_dirs, demo_name = _setup_config()
                                            ^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\gradio\reload.py", line 37, in _setup_config
    app_text = Path(original_path).read_text()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\pathlib.py", line 1059, in read_text
    return f.read()
           ^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0x9c in position 408: illegal multibyte sequence

**Comment by one-ok-code** [comment]
同样的问题
PS F:\Code\gpt\gpt-story-genius-main> gradio run.py
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Scripts\gradio.exe\__main__.py", line 7, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\gradio\cli.py", line 21, in cli
    gradio.reload.main()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\gradio\reload.py", line 88, in main
    filename, path, watch_dirs, demo_name = _setup_config()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\gradio\reload.py", line 37, in _setup_config
    app_text = Path(original_path).read_text()
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\pathlib.py", line 1233, in read_text
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x9c in position 394: illegal multibyte sequence

**Comment by LTX129** [comment]
> PS F:\gpt-story-genius> gradio run.py Traceback (most recent call last): File "", line 198, in _run_module_as_main File "", line 88, in _run_code File "C:\Python311\Scripts\gradio.exe__main__.py", line 7, in File "C:\Python311\Lib\site-packages\gradio\cli.py", line 21, in cli gradio.reload.main() File "C:\Python311\Lib\site-packages\gradio\reload.py", line 88, in main filename, path, watch_dirs, demo_name = _setup_config() ^^^^^^^^^^^^^^^ File "C:\Python311\Lib\site-packages\gradio\reload.py", line 37, in _setup_config app_text = Path(original_path).read_text() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Python311\Lib\pathlib.py", line 1059, in read_text return f.read() ^^^^^^^^ UnicodeDecodeError: 'gbk' codec can't decode byte 0x9c in position 408: illegal multibyte sequence

gradio版本太低，卸载了安装最新的就解决了

**Comment by LTX129** [comment]
> 同样的问题 PS F:\Code\gpt\gpt-story-genius-main> gradio run.py Traceback (most recent call last): File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Scripts\gradio.exe__main__.py", line 7, in File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\gradio\cli.py", line 21, in cli gradio.reload.main() File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\gradio\reload.py", line 88, in main filename, path, watch_dirs, demo_name = _setup_config() File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\gradio\reload.py", line 37, in _setup_config app_text = Path(original_path).read_text() File "c:\users\administrator\appdata\local\programs\python\python38\lib\pathlib.py", line 1233, in read_text return f.read() UnicodeDecodeError: 'gbk' codec can't decode byte 0x9c in position 394: illegal multibyte sequence

gradio版本太低，卸载了安装最新的就解决了
